## 1. Bronze

In [1]:
import pandas as pd

In [11]:
df = pd.read_csv(
    "DENGBR26.csv",
    encoding="latin1",
    sep=","
)

C:\Users\49048057809\AppData\Local\Temp\ipykernel_6256\3637943373.py:1: DtypeWarning: Columns (0: ID_OCUPA_N, 1: DT_CHIK_S1, 2: DT_CHIK_S2, 3: DT_PRNT) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

# 2. Silver

In [12]:
# lendo primeiras linhas
df.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2026-05-19,202620,2026,32,320400,32001.0,2448653.0,2026-05-14,...,0.0,0.0,0.0,0.0,0.0,0.0,2025-11-08,0,0.0,0.0
1,2,A90,2026-01-05,202601,2026,32,320500,32002.0,2499495.0,2026-01-04,...,0.0,0.0,0.0,0.0,0.0,0.0,2026-01-05,0,0.0,0.0
2,2,A90,2026-01-05,202601,2026,32,320500,32002.0,2522772.0,2026-01-05,...,0.0,0.0,0.0,0.0,0.0,0.0,2026-01-05,0,0.0,0.0
3,2,A90,2026-01-05,202601,2026,32,320500,32002.0,7838131.0,2026-01-04,...,0.0,0.0,0.0,0.0,0.0,0.0,2026-01-05,0,0.0,0.0
4,2,A90,2026-01-05,202601,2026,32,320530,32002.0,11789.0,2026-01-05,...,0.0,0.0,0.0,0.0,0.0,0.0,2026-01-05,0,0.0,0.0

In [14]:
# tamanho do meu dataframe
df.shape

(453398, 121)

In [15]:
# tipos de dados
df.dtypes

TP_NOT          int64
ID_AGRAVO         str
DT_NOTIFIC        str
SEM_NOT         int64
NU_ANO          int64
               ...
NDUPLIC_N     float64
DT_DIGITA         str
CS_FLXRET       int64
FLXRECEBI     float64
MIGRADO_W     float64
Length: 121, dtype: object

In [16]:
df["CS_RACA"].value_counts()

CS_RACA
4    260869
1    121487
9     41161
2     20925
3      7277
5      1679
Name: count, dtype: int64

In [17]:
# verificando valores nulos
df.isnull().sum()

TP_NOT             0
ID_AGRAVO          0
DT_NOTIFIC         0
SEM_NOT            0
NU_ANO             0
               ...
NDUPLIC_N     432306
DT_DIGITA          0
CS_FLXRET          0
FLXRECEBI     433824
MIGRADO_W     433825
Length: 121, dtype: int64

In [18]:
df["NDUPLIC_N"].value_counts()

NDUPLIC_N
0.0    19573
1.0     1519
Name: count, dtype: int64

In [19]:
nulos = pd.DataFrame({
    "quantidade_nulos": df.isnull().sum(),
    "porcentagem_nulos": (df.isnull().sum() / len(df)) * 100
})

# nulos = nulos[nulos["quantidade_nulos"] > 0]

nulos = nulos.sort_values(
    "quantidade_nulos",
    ascending=False
)

pd.set_option("display.max_rows", None)

print(nulos)

            quantidade_nulos  porcentagem_nulos
DT_CHIK_S2            453386          99.997353
DT_PRNT               453315          99.981694
DT_OBITO              452818          99.872077
DT_CHIK_S1            452797          99.867445
DT_GRAV               452584          99.820467
DT_VIRAL              451983          99.687912
DT_ALRM               440769          97.214589
DOENCA_TRA            433825          95.683042
LACO_N                433825          95.683042
PLAQ_MENOR            433825          95.683042
EPISTAXE              433825          95.683042
GENGIVO               433825          95.683042
MANI_HEMOR            433825          95.683042
SANGRAM               433825          95.683042
MIGRADO_W             433825          95.683042
COMPLICA              433825          95.683042
CON_FHD               433825          95.683042
PETEQUIAS             433825          95.683042
EVIDENCIA             433825          95.683042
PLASMATICO            433825          95.683042
HEMATURA              433825          95.683042
METRO                 433825          95.683042
FLXRECEBI             433824          95.682822
GRAV_MIOC             433030          95.507700
GRAV_ORGAO            433028          95.507259
GRAV_AST              433027          95.507038
GRAV_METRO            433026          95.506817
GRAV_SANG             433026          95.506817
GRAV_MELEN            433023          95.506156
GRAV_CONV             433022          95.505935
GRAV_ENCH             433022          95.505935
GRAV_CONSC            433022          95.505935
GRAV_HEMAT            433021          95.505715
GRAV_PULSO            433021          95.505715
GRAV_EXTRE            433020          95.505494
GRAV_TAQUI            433019          95.505274
GRAV_HIPOT            433019          95.505274
GRAV_INSUF            433016          95.504612
NDUPLIC_N             432306          95.348017
CLINC_CHIK            432293          95.345149
RES_CHIKS2            432213          95.327505
RESUL_PRNT            432205          95.325740
RES_CHIKS1            432106          95.303905
DT_INTERNA            427394          94.264642
ALRM_LIQ              421611          92.989162
ALRM_HEMAT            421610          92.988941
ALRM_HEPAT            421609          92.988721
ALRM_LETAR            421592          92.984971
ALRM_HIPOT            421581          92.982545
ALRM_VOM              421578          92.981883
ALRM_SANG             421557          92.977252
ALRM_ABDOM            421534          92.972179
ALRM_PLAQ             421532          92.971738
DT_PCR                411385          90.733748
MUNICIPIO             409033          90.214999
UF                    408461          90.088840
SOROTIPO              404737          89.267487
DT_SORO               380542          83.931116
DT_NS1                335661          74.032307
ID_OCUPA_N            288818          63.700766
HISTOPA_N             263632          58.145823
IMUNOH_N              263412          58.097301
RESUL_VI_N            234825          51.792244
RESUL_PCR_            223817          49.364355
RESUL_SORO            200933          44.317134
COMUNINF              186476          41.128545
COUFINF               185449          40.902033
COPAISINF             185430          40.897843
RESUL_NS1             178964          39.471722
TPAUTOCTO             164679          36.321069
EVOLUCAO              114409          25.233680
HOSPITALIZ            110272          24.321237
CRITERIO               89330          19.702337
CS_ESCOL_N             64300          14.181801
DT_ENCERRA             47623          10.503575
ID_RG_RESI             34704           7.654202
ID_REGIONA             33978           7.494078
CLASSI_FIN             32481           7.163905
CEFALEIA               15361           3.387973
VOMITO                 15361           3.387973
EXANTEMA               15361           3.387973
RENAL                  15361           3.387973
HEPATOPAT              15361           3.387973
HEMATOLOG              15361           3.387973
MIALGIA                15361           3.387973
FEBRE                  15361           3.387973
CONJUNTVIT             15361           3.387973
ARTRITE                15361           3.387973
ARTRALGIA              15361           3.387973
PETEQUIA_N             15361           3.387973
LEUCOPENIA             15361           3.387973
LACO                   15361           3.387973
HIPERTENSA             15361           3.387973
DOR_COSTAS             15361           3.387973
AUTO_IMUNE             15361           3.387973
ACIDO_PEPT             15361           3.387973
NAUSEA                 15361           3.387973
DIABETES               15361           3.387973
DOR_RETRO              15361           3.387973
DT_INVEST              15349           3.385326
TP_SISTEMA              4472           0.986330
ANO_NASC                1231           0.271505
CS_GESTANT                63           0.013895
ID_UNIDADE                60           0.013233
ID_MN_RESI                 7           0.001544
SG_UF_NOT                  0           0.000000
CS_RACA                    0           0.000000
SEM_NOT                    0           0.000000
ID_MUNICIP                 0           0.000000
DT_NOTIFIC                 0           0.000000
ID_AGRAVO                  0           0.000000
TP_NOT                     0           0.000000
NU_ANO                     0           0.000000
DT_SIN_PRI                 0           0.000000
CS_SEXO                    0           0.000000
SEM_PRI                    0           0.000000
NU_IDADE_N                 0           0.000000
ID_PAIS                    0           0.000000
SG_UF                      0           0.000000
CS_FLXRET                  0           0.000000
DT_DIGITA                  0           0.000000

In [20]:
# renomeando todas as colunas do df
df = df.rename(columns={
    "TP_NOT": "tipo_notificacao",
    "ID_AGRAVO": "id_agravo",
    "DT_NOTIFIC": "data_notificacao",
    "SEM_NOT": "semana_notificacao",
    "NU_ANO": "ano",
    "SG_UF_NOT": "uf_notificacao",
    "ID_MUNICIP": "id_municipio_notificacao",
    "ID_REGIONA": "id_regional",
    "ID_UNIDADE": "id_unidade",
    "DT_SIN_PRI": "data_primeiros_sintomas",
    "SEM_PRI": "semana_primeiros_sintomas",
    "ANO_NASC": "ano_nascimento",
    "NU_IDADE_N": "idade",
    "CS_SEXO": "sexo",
    "CS_GESTANT": "gestante",
    "CS_RACA": "raca",
    "CS_ESCOL_N": "escolaridade",
    "SG_UF": "uf",
    "ID_MN_RESI": "id_municipio_residencia",
    "ID_RG_RESI": "id_regional_residencia",
    "ID_PAIS": "id_pais",
    "DT_INVEST": "data_investigacao",
    "ID_OCUPA_N": "id_ocupacao",

    "FEBRE": "febre",
    "MIALGIA": "mialgia",
    "CEFALEIA": "cefaleia",
    "EXANTEMA": "exantema",
    "VOMITO": "vomito",
    "NAUSEA": "nausea",
    "DOR_COSTAS": "dor_costas",
    "CONJUNTVIT": "conjuntivite",
    "ARTRITE": "artrite",
    "ARTRALGIA": "artralgia",
    "PETEQUIA_N": "petequias",
    "LEUCOPENIA": "leucopenia",
    "LACO": "teste_laco",
    "DOR_RETRO": "dor_retro_orbital",
    "DIABETES": "diabetes",
    "HEMATOLOG": "doenca_hematologica",
    "HEPATOPAT": "hepatopatia",
    "RENAL": "doenca_renal",
    "HIPERTENSA": "hipertensao",
    "ACIDO_PEPT": "ulcera_peptica",
    "AUTO_IMUNE": "doenca_autoimune",

    "DT_CHIK_S1": "data_chikungunya_s1",
    "DT_CHIK_S2": "data_chikungunya_s2",
    "DT_PRNT": "data_prnt",
    "RES_CHIKS1": "resultado_chikungunya_s1",
    "RES_CHIKS2": "resultado_chikungunya_s2",
    "RESUL_PRNT": "resultado_prnt",

    "DT_SORO": "data_sorologia",
    "RESUL_SORO": "resultado_sorologia",
    "DT_NS1": "data_ns1",
    "RESUL_NS1": "resultado_ns1",
    "DT_VIRAL": "data_isolamento_viral",
    "RESUL_VI_N": "resultado_isolamento_viral",
    "DT_PCR": "data_pcr",
    "RESUL_PCR_": "resultado_pcr",
    "SOROTIPO": "sorotipo",
    "HISTOPA_N": "histopatologia",
    "IMUNOH_N": "imuno_histoquimica",

    "HOSPITALIZ": "hospitalizacao",
    "DT_INTERNA": "data_internacao",
    "UF": "uf_internacao",
    "MUNICIPIO": "municipio_internacao",
    "TPAUTOCTO": "tipo_autoctonia",
    "COUFINF": "uf_infeccao",
    "COPAISINF": "pais_infeccao",
    "COMUNINF": "municipio_infeccao",
    "CLASSI_FIN": "classificacao_final",
    "CRITERIO": "criterio_confirmacao",
    "DOENCA_TRA": "doenca_tratamento",
    "CLINC_CHIK": "classificacao_clinica_chikungunya",
    "EVOLUCAO": "evolucao",
    "DT_OBITO": "data_obito",
    "DT_ENCERRA": "data_encerramento",

    "ALRM_HIPOT": "alarme_hipotensao",
    "ALRM_PLAQ": "alarme_plaquetas",
    "ALRM_VOM": "alarme_vomito",
    "ALRM_SANG": "alarme_sangramento",
    "ALRM_HEMAT": "alarme_hematocrito",
    "ALRM_ABDOM": "alarme_dor_abdominal",
    "ALRM_LETAR": "alarme_letargia",
    "ALRM_HEPAT": "alarme_hepatomegalia",
    "ALRM_LIQ": "alarme_liquido",

    "DT_ALRM": "data_sinais_alarme",

    "GRAV_PULSO": "gravidade_pulso",
    "GRAV_CONV": "gravidade_convulsao",
    "GRAV_ENCH": "gravidade_enchimento_capilar",
    "GRAV_INSUF": "gravidade_insuficiencia",
    "GRAV_TAQUI": "gravidade_taquicardia",
    "GRAV_EXTRE": "gravidade_extremidades",
    "GRAV_HIPOT": "gravidade_hipotensao",
    "GRAV_HEMAT": "gravidade_hemorragia",
    "GRAV_MELEN": "gravidade_melena",
    "GRAV_METRO": "gravidade_metrorragia",
    "GRAV_SANG": "gravidade_sangramento",
    "GRAV_AST": "gravidade_ast",
    "GRAV_MIOC": "gravidade_miocardite",
    "GRAV_CONSC": "gravidade_consciencia",
    "GRAV_ORGAO": "gravidade_orgao",

    "DT_GRAV": "data_gravidade",

    "MANI_HEMOR": "manifestacao_hemorragica",
    "EPISTAXE": "epistaxe",
    "GENGIVO": "sangramento_gengival",
    "METRO": "metrorragia",
    "PETEQUIAS": "petequias",
    "HEMATURA": "hematúria",
    "SANGRAM": "sangramento",
    "LACO_N": "teste_laco_resultado",
    "PLASMATICO": "extravasamento_plasmatico",''
    "EVIDENCIA": "evidencia",
    "PLAQ_MENOR": "plaquetas_menores",
    "CON_FHD": "condicao_fhd",
    "COMPLICA": "complicacao",

    "TP_SISTEMA": "tipo_sistema",
    "NDUPLIC_N": "duplicidade",
    "DT_DIGITA": "data_digitacao",
    "CS_FLXRET": "fluxo_retorno",
    "FLXRECEBI": "fluxo_recebimento",
    "MIGRADO_W": "migrado"
})

In [21]:
# verificando as colunas renomeadas do df
print(df.columns.tolist())

['tipo_notificacao', 'id_agravo', 'data_notificacao', 'semana_notificacao', 'ano', 'uf_notificacao', 'id_municipio_notificacao', 'id_regional', 'id_unidade', 'data_primeiros_sintomas', 'semana_primeiros_sintomas', 'ano_nascimento', 'idade', 'sexo', 'gestante', 'raca', 'escolaridade', 'uf', 'id_municipio_residencia', 'id_regional_residencia', 'id_pais', 'data_investigacao', 'id_ocupacao', 'febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas', 'conjuntivite', 'artrite', 'artralgia', 'petequias', 'leucopenia', 'teste_laco', 'dor_retro_orbital', 'diabetes', 'doenca_hematologica', 'hepatopatia', 'doenca_renal', 'hipertensao', 'ulcera_peptica', 'doenca_autoimune', 'data_chikungunya_s1', 'data_chikungunya_s2', 'data_prnt', 'resultado_chikungunya_s1', 'resultado_chikungunya_s2', 'resultado_prnt', 'data_sorologia', 'resultado_sorologia', 'data_ns1', 'resultado_ns1', 'data_isolamento_viral', 'resultado_isolamento_viral', 'data_pcr', 'resultado_pcr', 'sorotipo', 'histopatologia', 'imuno_histoquimica', 'hospitalizacao', 'data_internacao', 'uf_internacao', 'municipio_internacao', 'tipo_autoctonia', 'uf_infeccao', 'pais_infeccao', 'municipio_infeccao', 'classificacao_final', 'criterio_confirmacao', 'doenca_tratamento', 'classificacao_clinica_chikungunya', 'evolucao', 'data_obito', 'data_encerramento', 'alarme_hipotensao', 'alarme_plaquetas', 'alarme_vomito', 'alarme_sangramento', 'alarme_hematocrito', 'alarme_dor_abdominal', 'alarme_letargia', 'alarme_hepatomegalia', 'alarme_liquido', 'data_sinais_alarme', 'gravidade_pulso', 'gravidade_convulsao', 'gravidade_enchimento_capilar', 'gravidade_insuficiencia', 'gravidade_taquicardia', 'gravidade_extremidades', 'gravidade_hipotensao', 'gravidade_hemorragia', 'gravidade_melena', 'gravidade_metrorragia', 'gravidade_sangramento', 'gravidade_ast', 'gravidade_miocardite', 'gravidade_consciencia', 'gravidade_orgao', 'data_gravidade', 'manifestacao_hemorragica', 'epistaxe', 'sangramento_gengival', 'metrorragia', 'petequias', 'hematúria', 'sangramento', 'teste_laco_resultado', 'extravasamento_plasmatico', 'evidencia', 'plaquetas_menores', 'condicao_fhd', 'complicacao', 'tipo_sistema', 'duplicidade', 'data_digitacao', 'fluxo_retorno', 'fluxo_recebimento', 'migrado']

In [22]:
# verificando linhas duplicadas 
print("Linhas duplicadas:", df.duplicated().sum())

Linhas duplicadas: 237

In [23]:
duplicadas = df[df.duplicated]

print(duplicadas)

        tipo_notificacao id_agravo data_notificacao  semana_notificacao   ano  \
8767                   2       A90       2026-05-04              202618  2026
11686                  2       A90       2026-05-27              202621  2026
15027                  2       A90       2026-07-10              202627  2026
15078                  2       A90       2026-07-09              202627  2026
15084                  2       A90       2026-07-09              202627  2026
15089                  2       A90       2026-07-09              202627  2026
15098                  2       A90       2026-07-09              202627  2026
15099                  2       A90       2026-07-09              202627  2026
16432                  2       A90       2026-07-27              202630  2026
17665                  2       A90       2026-08-12              202632  2026
17741                  2       A90       2026-08-13              202632  2026
18127                  2       A90       2026-08-19              202633  2026
18405                  2       A90       2026-08-20              202633  2026
18418                  2       A90       2026-08-20              202633  2026
19050                  2       A90       2026-08-31              202635  2026
21278                  2       A90       2026-08-28              202634  2026
21318                  2       A90       2026-08-24              202634  2026
24901                  2       A90       2026-07-23              202629  2026
26905                  2       A90       2026-07-06              202627  2026
27500                  2       A90       2026-07-25              202629  2026
33562                  2       A90       2026-08-01              202630  2026
37861                  2       A90       2026-08-13              202632  2026
37909                  2       A90       2026-07-30              202630  2026
41283                  2       A90       2026-04-16              202615  2026
46593                  2       A90       2026-07-14              202628  2026
47081                  2       A90       2026-04-21              202616  2026
47969                  2       A90       2026-08-12              202632  2026
51164                  2       A90       2026-06-15              202624  2026
51444                  2       A90       2026-05-17              202620  2026
51521                  2       A90       2026-05-11              202619  2026
51547                  2       A90       2026-05-18              202620  2026
51572                  2       A90       2026-08-09              202632  2026
51596                  2       A90       2026-04-25              202616  2026
51654                  2       A90       2026-05-02              202617  2026
51721                  2       A90       2026-04-30              202617  2026
51773                  2       A90       2026-05-01              202617  2026
51794                  2       A90       2026-05-02              202617  2026
51860                  2       A90       2026-05-17              202620  2026
51862                  2       A90       2026-05-17              202620  2026
51939                  2       A90       2026-05-01              202617  2026
51977                  2       A90       2026-05-18              202620  2026
52033                  2       A90       2026-05-01              202617  2026
52054                  2       A90       2026-05-17              202620  2026
52135                  2       A90       2026-05-18              202620  2026
52154                  2       A90       2026-02-17              202607  2026
52158                  2       A90       2026-05-01              202617  2026
57471                  2       A90       2026-08-19              202633  2026
59070                  2       A90       2026-06-02              202622  2026
60174                  2       A90       2026-06-08              202623  2026
62010                  2       A90       2026-02-23              202608  2026
62649                  2       A90       2026-08-13              202632  2026
63440                  2       A90       2026-05-11              202619  2026
63620                  2       A90       2026-08-30              202635  2026
68474                  2       A90       2026-03-13              202610  2026
70942                  2       A90       2026-04-11              202614  2026
74058                  2       A90       2026-08-21              202633  2026
74118                  2       A90       2026-08-18              202633  2026
82084                  2       A90       2026-04-15              202615  2026
83628                  2       A90       2026-04-18              202615  2026
94068                  2       A90       2026-07-05              202627  2026
95336                  2       A90       2026-06-15              202624  2026
97929                  2       A90       2026-05-05              202618  2026
98757                  2       A90       2026-03-10              202610  2026
99016                  2       A90       2026-02-21              202607  2026
108343                 2       A90       2026-08-25              202634  2026
113057                 2       A90       2026-03-17              202611  2026
120489                 2       A90       2026-09-01              202635  2026
121004                 2       A90       2026-04-18              202615  2026
121090                 2       A90       2026-04-25              202616  2026
121827                 2       A90       2026-02-21              202607  2026
122532                 2       A90       2026-08-25              202634  2026
122533                 2       A90       2026-08-25              202634  2026
123024                 2       A90       2026-04-06              202614  2026
123642                 2       A90       2026-03-27              202612  2026
127107                 2       A90       2026-09-01              202635  2026
128802                 2       A90       2026-04-02              202613  2026
130303                 2       A90       2026-09-01              202635  2026
130748                 2       A90       2026-04-04              202613  2026
134405                 2       A90       2026-05-17              202620  2026
134420                 2       A90       2026-08-25              202634  2026
134821                 2       A90       2026-05-02              202617  2026
135393                 2       A90       2026-09-01              202635  2026
135565                 2       A90       2026-05-06              202618  2026
136717                 2       A90       2026-04-20              202616  2026
137391                 2       A90       2026-03-04              202609  2026
139467                 2       A90       2026-05-04              202618  2026
139778                 2       A90       2026-03-16              202611  2026
139879                 2       A90       2026-03-11              202610  2026
140510                 2       A90       2026-04-03              202613  2026
141660                 2       A90       2026-03-22              202612  2026
145855                 2       A90       2026-09-01              202635  2026
145987                 2       A90       2026-05-13              202619  2026
147789                 2       A90       2026-06-11              202623  2026
148909                 2       A90       2026-08-12              202632  2026
149558                 2       A90       2026-03-09              202610  2026
149807                 2       A90       2026-05-21              202620  2026
150637                 2       A90       2026-03-26              202612  2026
150698                 2       A90       2026-02-27              202608  2026
151439                 2       A90       2026-05-22              202620  2026
154233                 2       A90       2026-04-06              202614  2026
157871                 2       A90       2026-04-14              202615  2026
158673                 2       A90       2026-03-03              202609  2026
159755                 2       A90       2026-03-18              202611  2026
161507                 2       A90       2026-05-26              202621  2026
164875                 2       A90       2026-05-05              202618  2026
165344                 2       A90       2026-06-15              202624  2026
165760                 2       A90       2026-05-10              202619  2026
166253                 2       A90       2026-05-30              202621  2026
166592                 2       A90       2026-04-28              202617  2026
166889                 2       A90       2026-05-05              202618  2026
167204                 2       A90       2026-05-12              202619  2026
167229                 2       A90       2026-07-23              202629  2026
167366                 2       A90       2026-07-17              202628  2026
168725                 2       A90       2026-07-24              202629  2026
169332                 2       A90       2026-05-21              202620  2026
170643                 2       A90       2026-05-15              202619  2026
171872                 2       A90       2026-01-19              202603  2026
174088                 2       A90       2026-01-16              202602  2026
174370                 2       A90       2026-05-08              202618  2026
176196                 2       A90       2026-04-28              202617  2026
177346                 2       A90       2026-03-24              202612  2026
177886                 2       A90       2026-04-25              202616  2026
179317                 2       A90       2026-03-06              202609  2026
181025                 2       A90       2026-04-05              202614  2026
181132                 2       A90       2026-03-23              202612  2026
197809                 2       A90       2026-03-16              202611  2026
207794                 2       A90       2026-01-12              202602  2026
209312                 2       A90       2026-03-23              202612  2026
216780                 2       A90       2026-06-25              202625  2026
220367                 2       A90       2026-08-14              202632  2026
220693                 2       A90       2026-08-25              202634  2026
223260                 2       A90       2026-08-15              202632  2026
228995                 2       A90       2026-03-03              202609  2026
230530                 2       A90       2026-03-24              202612  2026
230911                 2       A90       2026-05-27              202621  2026
231137                 2       A90       2026-03-22              202612  2026
233665                 2       A90       2026-06-10              202623  2026
236204                 2       A90       2026-04-30              202617  2026
242681                 2       A90       2026-08-19              202633  2026
243515                 2       A90       2026-07-10              202627  2026
244529                 2       A90       2026-07-17              202628  2026
245286                 2       A90       2026-03-25              202612  2026
249453                 2       A90       2026-08-17              202633  2026
254149                 2       A90       2026-05-21              202620  2026
256580                 2       A90       2026-04-02              202613  2026
257461                 2       A90       2026-03-21              202611  2026
258746                 2       A90       2026-01-29              202604  2026
261143                 2       A90       2026-08-07              202631  2026
261967                 2       A90       2026-05-29              202621  2026
262932                 2       A90       2026-04-26              202617  2026
263352                 2       A90       2026-02-25              202608  2026
274277                 2       A90       2026-05-05              202618  2026
284227                 2       A90       2026-03-20              202611  2026
286549                 2       A90       2026-07-08              202627  2026
286696                 2       A90       2026-03-24              202612  2026
288469                 2       A90       2026-03-20              202611  2026
289834                 2       A90       2026-07-11              202627  2026
290991                 2       A90       2026-03-11              202610  2026
300221                 2       A90       2026-07-19              202629  2026
301573                 2       A90       2026-09-03              202635  2026
308669                 2       A90       2026-07-02              202626  2026
309938                 2       A90       2026-07-09              202627  2026
310121                 2       A90       2026-08-17              202633  2026
311564                 2       A90       2026-05-10              202619  2026
312148                 2       A90       2026-06-05              202622  2026
312149                 2       A90       2026-06-05              202622  2026
313936                 2       A90       2026-08-12              202632  2026
313989                 2       A90       2026-08-25              202634  2026
314529                 2       A90       2026-07-27              202630  2026
314554                 2       A90       2026-03-18              202611  2026
314775                 2       A90       2026-07-12              202628  2026
319861                 2       A90       2026-06-15              202624  2026
320584                 2       A90       2026-06-12              202623  2026
320592                 2       A90       2026-06-11              202623  2026
321422                 2       A90       2026-06-23              202625  2026
322360                 2       A90       2026-06-02              202622  2026
322450                 2       A90       2026-06-02              202622  2026
323114                 2       A90       2026-05-26              202621  2026
323662                 2       A90       2026-01-13              202602  2026
324608                 2       A90       2026-06-20              202624  2026
324742                 2       A90       2026-06-02              202622  2026
325577                 2       A90       2026-05-30              202621  2026
325960                 2       A90       2026-06-20              202624  2026
325990                 2       A90       2026-06-15              202624  2026
326545                 2       A90       2026-05-23              202620  2026
327220                 2       A90       2026-03-02              202609  2026
327851                 2       A90       2026-06-21              202625  2026
327974                 2       A90       2026-06-15              202624  2026
328034                 2       A90       2026-06-08              202623  2026
328455                 2       A90       2026-03-17              202611  2026
328917                 2       A90       2026-06-23              202625  2026
329168                 2       A90       2026-06-18              202624  2026
329217                 2       A90       2026-06-13              202623  2026
329236                 2       A90       2026-06-09              202623  2026
329263                 2       A90       2026-06-15              202624  2026
329302                 2       A90       2026-06-21              202625  2026
329669                 2       A90       2026-05-13              202619  2026
330186                 2       A90       2026-06-18              202624  2026
331243                 2       A90       2026-06-08              202623  2026
331660                 2       A90       2026-08-10              202632  2026
331687                 2       A90       2026-06-11              202623  2026
332846                 2       A90       2026-08-17              202633  2026
339688                 2       A90       2026-03-04              202609  2026
341634                 2       A90       2026-09-01              202635  2026
351004                 2       A90       2026-03-24              202612  2026
351031                 2       A90       2026-03-04              202609  2026
351083                 2       A90       2026-04-08              202614  2026
351097                 2       A90       2026-03-19              202611  2026
351128                 2       A90       2026-03-18              202611  2026
352598                 2       A90       2026-08-13              202632  2026
354023                 2       A90       2026-04-20              202616  2026
355892                 2       A90       2026-01-14              202602  2026
357312                 2       A90       2026-08-03              202631  2026
357503                 2       A90       2026-08-28              202634  2026
358629                 2       A90       2026-08-27              202634  2026
358705                 2       A90       2026-03-04              202609  2026
360029                 2       A90       2026-08-12              202632  2026
360149                 2       A90       2026-01-31              202604  2026
363403                 2       A90       2026-04-27              202617  2026
363913                 2       A90       2026-05-18              202620  2026
364815                 2       A90       2026-03-18              202611  2026
366506                 2       A90       2026-02-26              202608  2026
367698                 2       A90       2026-04-28              202617  2026
383162                 2       A90       2026-02-08              202606  2026
385526                 2       A90       2026-04-10              202614  2026
391140                 2       A90       2026-05-01              202617  2026
415158                 2       A90       2026-08-05              202631  2026
420072                 2       A90       2026-03-27              202612  2026
421600                 2       A90       2026-03-13              202610  2026
423374                 2       A90       2026-02-25              202608  2026
426008                 2       A90       2026-09-01              202635  2026
427123                 2       A90       2026-02-23              202608  2026
432703                 2       A90       2026-02-25              202608  2026
435294                 2       A90       2026-06-08              202623  2026
444552                 2       A90       2026-01-14              202602  2026
453336                 2       A90       2026-08-18              202633  2026
453383                 2       A90       2026-02-19              202607  2026

        uf_notificacao  id_municipio_notificacao  id_regional  id_unidade  \
8767                32                    320500      32002.0   9958762.0
11686               32                    320500      32002.0   9958762.0
15027               32                    320500      32002.0   7838131.0
15078               32                    320500      32002.0   9958762.0
15084               32                    320500      32002.0   9958762.0
15089               32                    320500      32002.0   9958762.0
15098               32                    320500      32002.0   9958762.0
15099               32                    320500      32002.0   9958762.0
16432               32                    320500      32002.0   9958762.0
17665               32                    320500      32002.0   9958762.0
17741               32                    320500      32002.0   9958762.0
18127               32                    320500      32002.0   9958762.0
18405               32                    320500      32002.0   9958762.0
18418               32                    320500      32002.0   9958762.0
19050               32                    320500      32002.0   9958762.0
21278               12                    120060       1940.0   2000121.0
21318               12                    120040       1938.0   2000385.0
24901               27                    270030       1537.0   2004828.0

In [27]:
# converter datas
colunas_data = [
    "data_primeiros_sintomas",
    "data_investigacao",
    "data_chikungunya_s1",
    "data_chikungunya_s2",
    "data_prnt",
    "data_sorologia",
    "data_ns1",
    "data_isolamento_viral",
    "data_pcr",
    "data_internacao",
    "data_obito",
    "data_encerramento",
    "data_sinais_alarme",
    "data_gravidade",
    "data_digitacao"
]

for coluna in colunas_data:
    df[coluna] = pd.to_datetime(
        df[coluna],
        errors="coerce"
    )

# códigos para texto
colunas_codigo = [
    "id_agravo",
    "id_municipio_notificacao",
    "id_regional",
    "id_unidade",
    "id_municipio_residencia",
    "id_regional_residencia",
    "id_pais",
    "id_ocupacao",
    "uf_notificacao",
    "uf",
    "uf_infeccao",
    "pais_infeccao",
    "municipio_infeccao"
]

for coluna in colunas_codigo:
    df[coluna] = df[coluna].astype("string")

# variáveis categóricas
colunas_categoricas = [
    "tipo_notificacao",
    "sexo",
    "gestante",
    "raca",
    "escolaridade",
    "uf",
    "classificacao_final",
    "hospitalizacao",
    "evolucao",
    "criterio_confirmacao"
]

for coluna in colunas_categoricas:
    df[coluna] = df[coluna].astype("category")

df["idade"] = pd.to_numeric(
    df["idade"],
    errors="coerce"
).astype("Int64")

df["ano"] = pd.to_numeric(
    df["ano"],
    errors="coerce"
).astype("Int64")

df["ano_nascimento"] = pd.to_numeric(
    df["ano_nascimento"],
    errors="coerce"
).astype("Int64")

print(df.dtypes)

tipo_notificacao                           category
id_agravo                                    string
data_notificacao                                str
semana_notificacao                            int64
ano                                           Int64
uf_notificacao                               string
id_municipio_notificacao                     string
id_regional                                  string
id_unidade                                   string
data_primeiros_sintomas              datetime64[us]
semana_primeiros_sintomas                     int64
ano_nascimento                                Int64
idade                                         Int64
sexo                                       category
gestante                                   category
raca                                       category
escolaridade                               category
uf                                         category
id_municipio_residencia                      string
id_regional_residencia                       string
id_pais                                      string
data_investigacao                    datetime64[us]
id_ocupacao                                  string
febre                                       float64
mialgia                                     float64
cefaleia                                    float64
exantema                                    float64
vomito                                      float64
nausea                                      float64
dor_costas                                  float64
conjuntivite                                float64
artrite                                     float64
artralgia                                   float64
petequias                                   float64
leucopenia                                  float64
teste_laco                                  float64
dor_retro_orbital                           float64
diabetes                                    float64
doenca_hematologica                         float64
hepatopatia                                 float64
doenca_renal                                float64
hipertensao                                 float64
ulcera_peptica                              float64
doenca_autoimune                            float64
data_chikungunya_s1                  datetime64[us]
data_chikungunya_s2                  datetime64[us]
data_prnt                            datetime64[us]
resultado_chikungunya_s1                    float64
resultado_chikungunya_s2                    float64
resultado_prnt                              float64
data_sorologia                       datetime64[us]
resultado_sorologia                         float64
data_ns1                             datetime64[us]
resultado_ns1                               float64
data_isolamento_viral                datetime64[us]
resultado_isolamento_viral                  float64
data_pcr                             datetime64[us]
resultado_pcr                               float64
sorotipo                                    float64
histopatologia                              float64
imuno_histoquimica                          float64
hospitalizacao                             category
data_internacao                      datetime64[us]
uf_internacao                               float64
municipio_internacao                        float64
tipo_autoctonia                             float64
uf_infeccao                                  string
pais_infeccao                                string
municipio_infeccao                           string
classificacao_final                        category
criterio_confirmacao                       category
doenca_tratamento                           float64
classificacao_clinica_chikungunya           float64
evolucao                                   category
data_obito                           datetime64[us]
data_encerramento                    datetime64[us]
alarme_hipotensao                           float64
alarme_plaquetas                            float64
alarme_vomito                               float64
alarme_sangramento                          float64
alarme_hematocrito                          float64
alarme_dor_abdominal                        float64
alarme_letargia                             float64
alarme_hepatomegalia                        float64
alarme_liquido                              float64
data_sinais_alarme                   datetime64[us]
gravidade_pulso                             float64
gravidade_convulsao                         float64
gravidade_enchimento_capilar                float64
gravidade_insuficiencia                     float64
gravidade_taquicardia                       float64
gravidade_extremidades                      float64
gravidade_hipotensao                        float64
gravidade_hemorragia                        float64
gravidade_melena                            float64
gravidade_metrorragia                       float64
gravidade_sangramento                       float64
gravidade_ast                               float64
gravidade_miocardite                        float64
gravidade_consciencia                       float64
gravidade_orgao                             float64
data_gravidade                       datetime64[us]
manifestacao_hemorragica                    float64
epistaxe                                    float64
sangramento_gengival                        float64
metrorragia                                 float64
petequias                                   float64
hematúria                                   float64
sangramento                                 float64
teste_laco_resultado                        float64
extravasamento_plasmatico                   float64
evidencia                                   float64
plaquetas_menores                           float64
condicao_fhd                                float64
complicacao                                 float64
tipo_sistema                                float64
duplicidade                                 float64
data_digitacao                       datetime64[us]
fluxo_retorno                                 int64
fluxo_recebimento                           float64
migrado                                     float64
dtype: object

In [28]:
# removendo duplicados
print("Antes da remoção:", df.duplicated().sum())
df = df.drop_duplicates()
print("Após remoção:", df.duplicated().sum())
print("Tamanho do df pós remoção:", df.shape)

Antes da remoção: 237
Após remoção: 0
Tamanho do df pós remoção: (453161, 121)

In [29]:
# revisão geral

print("Volume de registros:", df.shape)
print("Volumes duplicados:", df.duplicated().sum())
print("Valores nulos", df.isnull().sum())

Volume de registros: (453161, 121)
Volumes duplicados: 0
Valores nulos tipo_notificacao                          0
id_agravo                                 0
data_notificacao                          0
semana_notificacao                        0
ano                                       0
uf_notificacao                            0
id_municipio_notificacao                  0
id_regional                           33964
id_unidade                               60
data_primeiros_sintomas                   0
semana_primeiros_sintomas                 0
ano_nascimento                         1231
idade                                     0
sexo                                      0
gestante                                 63
raca                                      0
escolaridade                          64241
uf                                        0
id_municipio_residencia                   7
id_regional_residencia                34689
id_pais                                   0
data_investigacao                     15304
id_ocupacao                          288641
febre                                 15316
mialgia                               15316
cefaleia                              15316
exantema                              15316
vomito                                15316
nausea                                15316
dor_costas                            15316
conjuntivite                          15316
artrite                               15316
artralgia                             15316
petequias                             15316
leucopenia                            15316
teste_laco                            15316
dor_retro_orbital                     15316
diabetes                              15316
doenca_hematologica                   15316
hepatopatia                           15316
doenca_renal                          15316
hipertensao                           15316
ulcera_peptica                        15316
doenca_autoimune                      15316
data_chikungunya_s1                  452560
data_chikungunya_s2                  453149
data_prnt                            453078
resultado_chikungunya_s1             431885
resultado_chikungunya_s2             431992
resultado_prnt                       431984
data_sorologia                       380314
resultado_sorologia                  200807
data_ns1                             335444
resultado_ns1                        178840
data_isolamento_viral                451746
resultado_isolamento_viral           234695
data_pcr                             411150
resultado_pcr                        223685
sorotipo                             404516
histopatologia                       263481
imuno_histoquimica                   263261
hospitalizacao                       110185
data_internacao                      427158
uf_internacao                        408240
municipio_internacao                 408812
tipo_autoctonia                      164574
uf_infeccao                          185342
pais_infeccao                        185323
municipio_infeccao                   186368
classificacao_final                   32420
criterio_confirmacao                  89235
doenca_tratamento                    433603
classificacao_clinica_chikungunya    432071
evolucao                             114301
data_obito                           452581
data_encerramento                     47546
alarme_hipotensao                    421360
alarme_plaquetas                     421311
alarme_vomito                        421357
alarme_sangramento                   421336
alarme_hematocrito                   421389
alarme_dor_abdominal                 421313
alarme_letargia                      421371
alarme_hepatomegalia                 421388
alarme_liquido                       421390
data_sinais_alarme                   440533
gravidade_pulso                      432799
gravidade_convulsao                  432800
gravidade_enchimento_capilar         432800
gravidade_insuficiencia              432794
gravidade_taquicardia                432797
gravidade_extremidades               432798
gravidade_hipotensao                 432797
gravidade_hemorragia                 432799
gravidade_melena                     432801
gravidade_metrorragia                432804
gravidade_sangramento                432804
gravidade_ast                        432805
gravidade_miocardite                 432808
gravidade_consciencia                432800
gravidade_orgao                      432806
data_gravidade                       452347
manifestacao_hemorragica             433603
epistaxe                             433603
sangramento_gengival                 433603
metrorragia                          433603
petequias                            433603
hematúria                            433603
sangramento                          433603
teste_laco_resultado                 433603
extravasamento_plasmatico            433603
evidencia                            433603
plaquetas_menores                    433603
condicao_fhd                         433603
complicacao                          433603
tipo_sistema                           4453
duplicidade                          432085
data_digitacao                            0
fluxo_retorno                             0
fluxo_recebimento                    433602
migrado                              433603
dtype: int64

In [30]:
nulos = pd.DataFrame({
    "quantidade_nulos": df.isnull().sum(),
    "porcentagem_nulos": (df.isnull().sum() / len(df)) * 100
})

# nulos = nulos[nulos["quantidade_nulos"] > 0]

nulos = nulos.sort_values(
    "quantidade_nulos",
    ascending=False
)

pd.set_option("display.max_rows", None)

print(nulos)

                                   quantidade_nulos  porcentagem_nulos
data_chikungunya_s2                          453149          99.997352
data_prnt                                    453078          99.981684
data_obito                                   452581          99.872010
data_chikungunya_s1                          452560          99.867376
data_gravidade                               452347          99.820373
data_isolamento_viral                        451746          99.687749
data_sinais_alarme                           440533          97.213352
doenca_tratamento                            433603          95.684095
teste_laco_resultado                         433603          95.684095
plaquetas_menores                            433603          95.684095
epistaxe                                     433603          95.684095
sangramento_gengival                         433603          95.684095
manifestacao_hemorragica                     433603          95.684095
sangramento                                  433603          95.684095
migrado                                      433603          95.684095
complicacao                                  433603          95.684095
condicao_fhd                                 433603          95.684095
petequias                                    433603          95.684095
evidencia                                    433603          95.684095
extravasamento_plasmatico                    433603          95.684095
hematúria                                    433603          95.684095
metrorragia                                  433603          95.684095
fluxo_recebimento                            433602          95.683874
gravidade_miocardite                         432808          95.508660
gravidade_orgao                              432806          95.508219
gravidade_ast                                432805          95.507998
gravidade_metrorragia                        432804          95.507778
gravidade_sangramento                        432804          95.507778
gravidade_melena                             432801          95.507116
gravidade_convulsao                          432800          95.506895
gravidade_enchimento_capilar                 432800          95.506895
gravidade_consciencia                        432800          95.506895
gravidade_hemorragia                         432799          95.506674
gravidade_pulso                              432799          95.506674
gravidade_extremidades                       432798          95.506454
gravidade_taquicardia                        432797          95.506233
gravidade_hipotensao                         432797          95.506233
gravidade_insuficiencia                      432794          95.505571
duplicidade                                  432085          95.349114
classificacao_clinica_chikungunya            432071          95.346025
resultado_chikungunya_s2                     431992          95.328592
resultado_prnt                               431984          95.326826
resultado_chikungunya_s1                     431885          95.304980
data_internacao                              427158          94.261863
alarme_liquido                               421390          92.989026
alarme_hematocrito                           421389          92.988805
alarme_hepatomegalia                         421388          92.988585
alarme_letargia                              421371          92.984833
alarme_hipotensao                            421360          92.982406
alarme_vomito                                421357          92.981744
alarme_sangramento                           421336          92.977110
alarme_dor_abdominal                         421313          92.972034
alarme_plaquetas                             421311          92.971593
data_pcr                                     411150          90.729343
municipio_internacao                         408812          90.213412
uf_internacao                                408240          90.087188
sorotipo                                     404516          89.265405
data_sorologia                               380314          83.924698
data_ns1                                     335444          74.023140
id_ocupacao                                  288641          63.695022
histopatologia                               263481          58.142912
imuno_histoquimica                           263261          58.094364
resultado_isolamento_viral                   234695          51.790644
resultado_pcr                                223685          49.361044
resultado_sorologia                          200807          44.312507
municipio_infeccao                           186368          41.126222
uf_infeccao                                  185342          40.899813
pais_infeccao                                185323          40.895620
resultado_ns1                                178840          39.465003
tipo_autoctonia                              164574          36.316894
evolucao                                     114301          25.223044
hospitalizacao                               110185          24.314758
criterio_confirmacao                          89235          19.691677
escolaridade                                  64241          14.176198
data_encerramento                             47546          10.492077
id_regional_residencia                        34689           7.654895
id_regional                                   33964           7.494908
classificacao_final                           32420           7.154190
cefaleia                                      15316           3.379814
vomito                                        15316           3.379814
exantema                                      15316           3.379814
doenca_renal                                  15316           3.379814
hepatopatia                                   15316           3.379814
doenca_hematologica                           15316           3.379814
mialgia                                       15316           3.379814
febre                                         15316           3.379814
conjuntivite                                  15316           3.379814
artrite                                       15316           3.379814
artralgia                                     15316           3.379814
petequias                                     15316           3.379814
leucopenia                                    15316           3.379814
teste_laco                                    15316           3.379814
hipertensao                                   15316           3.379814
dor_costas                                    15316           3.379814
doenca_autoimune                              15316           3.379814
ulcera_peptica                                15316           3.379814
nausea                                        15316           3.379814
diabetes                                      15316           3.379814
dor_retro_orbital                             15316           3.379814
data_investigacao                             15304           3.377166
tipo_sistema                                   4453           0.982653
ano_nascimento                                 1231           0.271647
gestante                                         63           0.013902
id_unidade                                       60           0.013240
id_municipio_residencia                           7           0.001545
uf_notificacao                                    0           0.000000
raca                                              0           0.000000
semana_notificacao                                0           0.000000
id_municipio_notificacao                          0           0.000000
data_notificacao                                  0           0.000000
id_agravo                                         0           0.000000
tipo_notificacao                                  0           0.000000
ano                                               0           0.000000
data_primeiros_sintomas                           0           0.000000
sexo                                              0           0.000000
semana_primeiros_sintomas                         0           0.000000
idade                                             0           0.000000
id_pais                                           0           0.000000
uf                                                0           0.000000
fluxo_retorno                                     0           0.000000
data_digitacao                                    0           0.000000

In [31]:
colunas = [
    "ano",
    "data_primeiros_sintomas",
    "idade",
    "sexo",
    "raca",
    "gestante",
    "uf",
    "id_municipio_residencia",
    "classificacao_final",
    "hospitalizacao",
    "evolucao",
    "duplicidade",
    "id_regional",
    "febre",
    "mialgia",
    "cefaleia",
    "vomito",
    "dor_costas",
    "nausea",
    "dor_retro_orbital"
]

In [32]:
df_dengue = df[colunas]

df_dengue.head()

,ano,data_primeiros_sintomas,idade,sexo,raca,gestante,uf,id_municipio_residencia,classificacao_final,hospitalizacao,evolucao,duplicidade,id_regional,febre,mialgia,cefaleia,vomito,dor_costas,nausea,dor_retro_orbital
0,2026,2026-05-14,4048,F,1,5.0,32,320400.0,10.0,2.0,1.0,0.0,32001.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0
1,2026,2026-01-04,4041,F,4,5.0,32,320500.0,10.0,2.0,1.0,0.0,32002.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0
2,2026,2026-01-05,4034,F,2,5.0,32,320500.0,10.0,2.0,1.0,0.0,32002.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0
3,2026,2026-01-04,4027,M,4,6.0,32,320500.0,10.0,2.0,9.0,0.0,32002.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0
4,2026,2026-01-05,4028,M,4,6.0,32,320530.0,10.0,2.0,1.0,0.0,32002.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0